version: '3'

services:

    postgres:
        image: postgres:latest

    esi-nginx:
        image: nginx:alpine
        volumes:
          - ./infra/esi-cache/nginx-esi.conf:/etc/nginx/nginx.conf:ro

    esi-varnish:
        image: million12/varnish
        environment:
          - VCL_CONFIG=/varnish-esi.vcl
        volumes:
          - ./infra/esi-cache/varnish-esi.vcl:/varnish-esi.vcl:ro
        links:
          - esi-nginx
        depends_on:
          - esi-nginx

    zkill-nginx:
        image: nginx:alpine
        volumes:
          - ./infra/zkill-cache/nginx-zkill.conf:/etc/nginx/nginx.conf:ro
    zkill-varnish:
        image: million12/varnish
        environment:
          - VCL_CONFIG=/varnish-zkill.vcl
        volumes:
          - ./infra/zkill-cache/varnish-zkill.vcl:/varnish-zkill.vcl:ro
        links:
          - zkill-nginx
        depends_on:
          - zkill-nginx

    api-image:
        build: .
        image: evebook/api
        entrypoint: echo "Image-only service is not intended to be run, exiting."

    api:
        command: yarn run start
        image: evebook/api
        env_file:
          - .env
        ports:
          - "3000:3000"
        volumes:
          - .:/app/src
          - /app/src/node_modules
        links:
          - postgres
          - esi-varnish
          - zkill-varnish
        depends_on:
          - postgres
          - esi-varnish
          - zkill-varnish

    updater:
        command: yarn run start:updater
        image: evebook/api
        env_file:
          - .env
        ports:
          - "3001:3001"
        volumes:
          - .:/app/src
          - /app/src/node_modules
        links:
          - postgres
          - esi-varnish
        depends_on:
          - postgres
          - esi-varnish

    killmails:
        command: yarn run start:killmails
        image: evebook/api
        env_file:
          - .env
        ports:
          - "3002:3002"
        volumes:
          - .:/app/src
          - /app/src/node_modules
        links:
          - postgres
          - esi-varnish
        depends_on:
          - postgres
          - esi-varnish
  