---
apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: api-evebook-online
  namespace: default
spec:
  domains:
  - api.evebook.online
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: gce
      credentialSecretName: voyager-gce
